//nome: Crislean Santos Martins ra: 1913280
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author crisl
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitulodejFrame = new javax.swing.JLabel();
        mnBar = new javax.swing.JMenuBar();
        Cadastro = new javax.swing.JMenu();
        mnSemAlcool = new javax.swing.JMenuItem();
        mnAlcoolico = new javax.swing.JMenuItem();
        msSemAcucar = new javax.swing.JMenuItem();
        Sair = new javax.swing.JMenu();
        FecharApp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Maquina de Bebidas");

        TitulodejFrame.setFont(TitulodejFrame.getFont().deriveFont((TitulodejFrame.getFont().getStyle() | java.awt.Font.ITALIC) & ~java.awt.Font.BOLD, TitulodejFrame.getFont().getSize()+6));
        TitulodejFrame.setText("Maquina de Bebidas");

        Cadastro.setText("Cadastro");

        mnSemAlcool.setText("Sem Alcool");
        mnSemAlcool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSemAlcoolActionPerformed(evt);
            }
        });
        Cadastro.add(mnSemAlcool);

        mnAlcoolico.setText("Alcoolico");
        mnAlcoolico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAlcoolicoActionPerformed(evt);
            }
        });
        Cadastro.add(mnAlcoolico);

        msSemAcucar.setText("Sem Açucar");
        msSemAcucar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msSemAcucarActionPerformed(evt);
            }
        });
        Cadastro.add(msSemAcucar);

        mnBar.add(Cadastro);

        Sair.setText("Sair");

        FecharApp.setText("Fechar");
        FecharApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharAppActionPerformed(evt);
            }
        });
        Sair.add(FecharApp);

        mnBar.add(Sair);

        setJMenuBar(mnBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(TitulodejFrame)
                .addContainerGap(293, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(TitulodejFrame)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnSemAlcoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSemAlcoolActionPerformed
        CadSemAlcool.getCadSemAlcool().setVisible(true);
        
    }//GEN-LAST:event_mnSemAlcoolActionPerformed

    private void FecharAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharAppActionPerformed
        sair();
    }//GEN-LAST:event_FecharAppActionPerformed

    private void mnAlcoolicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAlcoolicoActionPerformed
        CadAlcoolico.getCadAlcoolico().setVisible(true);
    }//GEN-LAST:event_mnAlcoolicoActionPerformed

    private void msSemAcucarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msSemAcucarActionPerformed
        CadSemAcucar.getCadSemAlcucar().setVisible(true);
    }//GEN-LAST:event_msSemAcucarActionPerformed

    public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja sair?", "Saida", JOptionPane.YES_NO_CANCEL_OPTION);
        if(resp == 0){
            this.dispose();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Cadastro;
    private javax.swing.JMenuItem FecharApp;
    private javax.swing.JMenu Sair;
    private javax.swing.JLabel TitulodejFrame;
    private javax.swing.JMenuItem mnAlcoolico;
    private javax.swing.JMenuBar mnBar;
    private javax.swing.JMenuItem mnSemAlcool;
    private javax.swing.JMenuItem msSemAcucar;
    // End of variables declaration//GEN-END:variables
}
